# Generated by Django 5.2.11 on 2026-02-07 07:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(help_text='13 Character ISBN number', max_length=13, unique=True)),
                ('isbn_10', models.CharField(blank=True, help_text='10 Character ISBN number', max_length=10, null=True)),
                ('author', models.CharField(max_length=255)),
                ('co_authors', models.TextField(blank=True, help_text='Comma-separated list of co-authors', null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('format', models.CharField(default='Paperback', help_text='e.g., Hardcover, Paperback, eBook', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('location', models.CharField(help_text='Shelf/Rack location in library', max_length=100)),
                ('call_number', models.CharField(help_text='Library classification number', max_length=50, unique=True)),
                ('total_copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for search', null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['isbn'], name='catalog_boo_isbn_43f845_idx'), models.Index(fields=['title'], name='catalog_boo_title_3a1ffe_idx'), models.Index(fields=['author'], name='catalog_boo_author_66025a_idx'), models.Index(fields=['status'], name='catalog_boo_status_b30b19_idx')],
            },
        ),
    ]
