# Generated by Django 5.2.11 on 2026-02-07 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='issued_by',
            field=models.ForeignKey(help_text='Staff member who issued the book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member who received the returned book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'book', 'status')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_9cef77_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['book', 'status'], name='transaction_book_id_f46085_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['due_date'], name='transaction_due_dat_507052_idx'),
        ),
    ]
